const students= [{
    "id": 1,
    "first_name": "Carolyn",
    "last_name": "Labes",
    "email": "clabes0@tinypic.com"
  }, {
    "id": 2,
    "first_name": "Porty",
    "last_name": "de Nore",
    "email": "pdenore1@barnesandnoble.com"
  }, {
    "id": 3,
    "first_name": "Carson",
    "last_name": "Besant",
    "email": "cbesant2@mac.com"
  }, {
    "id": 4,
    "first_name": "Emmy",
    "last_name": "Mantrip",
    "email": "emantrip3@japanpost.jp"
  }, {
    "id": 5,
    "first_name": "Ezra",
    "last_name": "Wollrauch",
    "email": "ewollrauch4@51.la"
  }, {
    "id": 6,
    "first_name": "Damara",
    "last_name": "Pahl",
    "email": "dpahl5@bloglovin.com"
  }, {
    "id": 7,
    "first_name": "Marlena",
    "last_name": "Gounot",
    "email": "mgounot6@reddit.com"
  }, {
    "id": 8,
    "first_name": "Carter",
    "last_name": "Kubiak",
    "email": "ckubiak7@cdc.gov"
  }, {
    "id": 9,
    "first_name": "Elyn",
    "last_name": "Lanphier",
    "email": "elanphier8@google.nl"
  }, {
    "id": 10,
    "first_name": "Ikey",
    "last_name": "Kilsby",
    "email": "ikilsby9@redcross.org"
  }]
module.exports = students